name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: checkout code
        uses: actions/checkout@v4
    - name: set up miniconda 
      uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10  # Set your Python version
          activate-environment: base
          auto-update-conda: true
          use-mamba: true  
    - name: Install dependencies
      run: |
        conda env create --file environment.yml 
    - name: Activate conda env
      run: |
        conda activate actipy_env
    - name: Test with makefile
      run: |
        make all 
