name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up miniconda 
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9  # Set your Python version
          miniconda-version: latest
          activate-environment: test
          auto-update-conda: true
          use-mamba: true  
      - name: Install dependencies
        run: |
          conda env update --file environment.yml 
      - name: Activate conda env
        run: |
          conda activate actipy_env
      - name: Test with makefile
        run: |
          make all 
