name: Python Package using Conda

on: [push]

jobs:
  test:
    runs-on: macos-13
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up miniconda 
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          activate-environment: circapy_env
          environment-file: environment.yml
          auto-update-conda: true
          use-mamba: true  
      - name: Test with makefile
        shell: bash -l {0}
        run: |
          conda info 
          make all 
